Repository pushingkarmaorg/python-plexapi, pull requests merged in 2021-07, with the labels that each got.

#780 Remove manual sorts/fields added to PMS
  plexapi/library.py
  tests/test_library.py
Labels: non-breaking

#781 Add ability to parse the smart filters from collections and playlists
  plexapi/collection.py
  plexapi/library.py
  plexapi/mixins.py
  plexapi/playlist.py
  plexapi/utils.py
  tests/test_collection.py
  tests/test_playlist.py
  tests/test_utils.py
Labels: non-breaking

#783 Add ability to move items in a collection
  plexapi/collection.py
  plexapi/playlist.py
  tests/test_collection.py
  tests/test_library.py
  tests/test_video.py
Labels: non-breaking

#788 Add ability to use FilterChoice and FilteringSort objects in library search
  plexapi/library.py
  tests/test_library.py
Labels: non-breaking

#798 Fix sync headers
  plexapi/myplex.py
  plexapi/sync.py
Labels: non-breaking

#792 Add GitHub Actions to Dependabot
  .github/dependabot.yml
Labels: dependencies

#797 Add producers, roles, and hasCommercialMarker to Episode objects
  plexapi/media.py
  plexapi/video.py
  tests/test_video.py
Labels: non-breaking

#800 Decouple resource address sorting from connection attempts
  plexapi/myplex.py
Labels: non-breaking

#782 Add playlist title search and sorting
  plexapi/library.py
  plexapi/server.py
  tests/conftest.py
  tests/test_library.py
Labels: breaking

#799 Add libtype argument for creating smart playlists
  plexapi/collection.py
  plexapi/playlist.py
  plexapi/server.py
  tests/test_playlist.py
Labels: breaking

#804 Deprecate Python 3.5
  setup.py
Labels: breaking, dependencies
